# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
R -e 'install.packages("knitr")'

os:
  - linux
  - osx

r:
  - oldrel
  - release

install:
  - Rscript -e 'install.packages("knitr")'

after_success:
  - Rscript -e 'covr::codecov(type = "all")'
